export const tableList = [
  {
    id: "1",
    name: "High Vibration",
    status: "Possible leak in the system",
    area: "Separator",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "57%",
  },
  {
    id: "2",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "3",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "4",
    name: "Low Pressure",
    status: "Excessive vibration detected in equipment",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "97%",
  },
  {
    id: "5",
    name: "High Vibration",
    status: "Possible leak in the system",
    area: "Separator",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "57%",
  },
  {
    id: "6",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "7",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "8",
    name: "Low Pressure",
    status: "Excessive vibration detected in equipment",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "97%",
  },
  {
    id: "9",
    name: "High Vibration",
    status: "Possible leak in the system",
    area: "Separator",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "57%",
  },
  {
    id: "10",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "11",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "12",
    name: "Low Pressure",
    status: "Excessive vibration detected in equipment",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "97%",
  },
  {
    id: "13",
    name: "High Vibration",
    status: "Possible leak in the system",
    area: "Separator",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "57%",
  },
  {
    id: "14",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "15",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "16",
    name: "Low Pressure",
    status: "Excessive vibration detected in equipment",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "97%",
  },
  {
    id: "17",
    name: "High Vibration",
    status: "Possible leak in the system",
    area: "Separator",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "57%",
  },
  {
    id: "18",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "19",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "20",
    name: "Low Pressure",
    status: "Excessive vibration detected in equipment",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "97%",
  },
  {
    id: "21",
    name: "High Vibration",
    status: "Possible leak in the system",
    area: "Separator",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "57%",
  },
  {
    id: "22",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "23",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "24",
    name: "Low Pressure",
    status: "Excessive vibration detected in equipment",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "97%",
  },
  {
    id: "21",
    name: "High Vibration",
    status: "Possible leak in the system",
    area: "Separator",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "57%",
  },
  {
    id: "22",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "23",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "24",
    name: "Low Pressure",
    status: "Excessive vibration detected in equipment",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "97%",
  },
  {
    id: "21",
    name: "High Vibration",
    status: "Possible leak in the system",
    area: "Separator",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "57%",
  },
  {
    id: "22",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "23",
    name: "Flow Anomaly",
    status: "Pressure below normal operating range",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "29%",
  },
  {
    id: "24",
    name: "Low Pressure",
    status: "Excessive vibration detected in equipment",
    area: "Wellhead",
    severity: "Medium",
    date: "19:29",
    time: "7/23/2024",
    started: "97%",
  },
];
export const reportList = [
  {
    id: "1",
    name: "Project-Vision",
    file: "PDF",
    category: "Planning",
    author: "Alice Johnson",
    status: "sent",
  },
  {
    id: "2",
    name: "Project-Vision",
    file: "XLSX",
    category: "Research",
    author: "James Johnson",
    status: "progress",
  },
  {
    id: "2",
    name: "Project-Vision",
    file: "XLSX",
    category: "Design",
    author: "Maria Johnson",
    status: "pending",
  },
  {
    id: "1",
    name: "Project-Vision",
    file: "PDF",
    category: "Planning",
    author: "Alice Johnson",
    status: "sent",
  },
  {
    id: "2",
    name: "Project-Vision",
    file: "XLSX",
    category: "Research",
    author: "James Johnson",
    status: "progress",
  },
  {
    id: "2",
    name: "Project-Vision",
    file: "XLSX",
    category: "Design",
    author: "Maria Johnson",
    status: "pending",
  },
  {
    id: "1",
    name: "Project-Vision",
    file: "PDF",
    category: "Planning",
    author: "Alice Johnson",
    status: "sent",
  },
  {
    id: "2",
    name: "Project-Vision",
    file: "XLSX",
    category: "Research",
    author: "James Johnson",
    status: "progress",
  },
  {
    id: "2",
    name: "Project-Vision",
    file: "XLSX",
    category: "Design",
    author: "Maria Johnson",
    status: "pending",
  },
  {
    id: "1",
    name: "Project-Vision",
    file: "PDF",
    category: "Planning",
    author: "Alice Johnson",
    status: "sent",
  },
  {
    id: "2",
    name: "Project-Vision",
    file: "XLSX",
    category: "Research",
    author: "James Johnson",
    status: "progress",
  },
  {
    id: "2",
    name: "Project-Vision",
    file: "XLSX",
    category: "Design",
    author: "Maria Johnson",
    status: "pending",
  },
];
